services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=zaq1@WSX
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
volumes:
  pgdata:
  mongoData: